---@class PilotTemplateData dataset for creating a new pilot template
---@field Sprite string the sprite sheet for the pilot
---@field Voice PilotVoices the voice used by the pilot
---@field Name string the name of the pilot, also used as a value to lookup the reference, Recommended to use full uppercase as this is what the game does
---@field Level number the level of the pilot
---@field LevelExperience number the amount of experience in the current level
---@field Skill number the skill stat of the pilot (0-100)
---@field Reaction number the reaction stat of the pilot (0-100)
---@field Vitality number the vitality stat of the pilot (0-100)
---@field StressResistance number the stress resistance stat of the pilot (0-100)

---@class PilotCreationData dataset for adding a new pilot
---@field Template number|PilotNames the base dataset to base the pilot on, either the index number in obj_database.pilot_stat or reference one of the existing pilots. this wil determine the used sprite.
---@field WorkExperience ReferencedLocalizedString the description text for the work experience of the pilot.
---@field Age number the age of the pilot
---@field IsCyborg boolean if true the pilot is a cyborg
---@field Name string? the name for the pilot, leave nil to use the template settings
---@field Voice PilotVoices? the voice used by the pilot, leave nil to use the template settings
---@field Level number? the level of the pilot, leave nil to use the template settings
---@field LevelExperience number? the amount of experience in the current level
---@field Skill number? the skill stat of the pilot (0-100), leave nil to use the template settings
---@field Reaction number? the reaction stat of the pilot (0-100), leave nil to use the template settings
---@field Vitality number? the vitality stat of the pilot (0-100), leave nil to use the template settings
---@field StressResistance number? the stress resistance stat of the pilot (0-100), leave nil to use the template settings

---@class LocalizedPilotCreationData localized dataset for adding a new pilot
---@field Template number|PilotNames the base dataset to base the pilot on, either the index number in obj_database.pilot_stat or reference one of the existing pilots. this wil determine the used sprite.
---@field WorkExperience string the description text for the work experience of the pilot.
---@field Age number the age of the pilot
---@field IsCyborg boolean if true the pilot is a cyborg
---@field Name string? the name for the pilot, leave nil to use the template settings
---@field Voice PilotVoices? the voice used by the pilot, leave nil to use the template settings
---@field Level number? the level of the pilot, leave nil to use the template settings
---@field LevelExperience number? the amount of experience in the current level
---@field Skill number? the skill stat of the pilot (0-100), leave nil to use the template settings
---@field Reaction number? the reaction stat of the pilot (0-100), leave nil to use the template settings
---@field Vitality number? the vitality stat of the pilot (0-100), leave nil to use the template settings
---@field StressResistance number? the stress resistance stat of the pilot (0-100), leave nil to use the template settings

---@class PilotDsMap the converted dataset for a pilot ds_map
---@field Index number the index of the ds_map in obj_database.pilot_stat
---@field Sprite number the sprite index
---@field SoundIndex string the sound index value
---@field PhraseNumber number the phrase number
---@field Name string the name of the pilot
---@field Level number the level of the pilot
---@field LevelExperience number the amount of experience in the current level
---@field Skill number the skill stat of the pilot (0-100)
---@field Reaction number the reaction stat of the pilot (0-100)
---@field Vitality number the vitality stat of the pilot (0-100)
---@field StressResistance number the stress resistance stat of the pilot (0-100)