---@class SolenoidCreationData Dataset for adding a new solenoid to the obj database.
---@field ReferenceName string The reference name of the solenoid, used to find its references.
---@field ComponentSize ComponentSize the size of the component when constructing it.
---@field IsResearched boolean True if the component is researched from the start of the game, false otherwise.
---@field CanBeConstructed boolean True if it can be constructed in the component shop, false otherwise.
---@field GiveFreeItem boolean True if a free copy is created when triggered as an unlock, false otherwise.
---@field PriceMetallite number The amount of metallite needed to produce this solenoid.
---@field PriceBjorn number The amount of bjorn needed to produce this solenoid.
---@field PriceMunilon number The amount of munilon needed to produce this solenoid.
---@field PriceSkalaknit number The amount of skalaknit needed to produce this solenoid.
---@field PriceStaff number The amount of staff needed to produce this solenoid.
---@field ProductionDays number The amount of days it takes to produce this solenoid.
---@field Power number The power value of the solenoid, lower numbers give more heat resist on reactor.
---@field Induction number The induction value of the solenoid, any deviation from 1 gives worse energy stats.
---@field Sprite string The sprite for the solenoid.