---This is an auto generated class definition.
---
---Please use the found values as a starting point for your use.
---As not all values may be present at every point of the game.
---Or values could be missing from the definition.
---@class game_obj_component
---@field comp_data_type number The index number of the component.
---@field comp_type GameComponentType The type of component.
---@field CustomData ModdedComponentCustomData? --A Framework added object the containing data used to handle custom components.
---@field depth number The current depth lower number are drawn in front of high number depths.
---@field item_pos number
---@field logo number The index of the sprite, use -4 to auto set it.
---@field logo_index number
---@field researched boolean True if it can be constructed, false otherwise.
---@field size ComponentSize The size of the component when constructing it.
---@field size_x number
---@field size_y number
---@field x number The x position of the instance
---@field y number The y position of the instance