---This is an auto generated class definition.
---
---Please use the found values as a starting point for your use.
---As not all values may be present at every point of the game.
---Or values could be missing from the definition.
---@class game_obj_research
---@field array_lua table
---@field blink number
---@field check_research number
---@field condition ResearchCondition the state condition the research is in (0-closed, 1-opened, 2-researching, 3-researched)
---@field give_item boolean when true indicates the research will give a free item upon completion
---@field just_researched boolean
---@field link table
---@field ln_res table
---@field meet boolean
---@field n_ln_res number
---@field new_research boolean
---@field next_day boolean
---@field opened number
---@field progression number
---@field require_days number the remaining days to complete the research
---@field require_days_max number the initial required days to complete the research
---@field require_staff number the number of required staff to research
---@field res_number number the number for the research as found in the debug (F6) of the research screen (upper left white number)
---@field res_type number
---@field res_under_type number
---@field researching_anim number
---@field st_lua table
---@field text string
---@field text_days string
---@field text_staff string