---This is an auto generated class definition.
---
---Please use the found values as a starting point for your use.
---As not all values may be present at every point of the game.
---Or values could be missing from the definition.
---@class game_obj_content_reactor
---@field size_x number
---@field position_y number
---@field sort_anim number
---@field sort_now boolean
---@field array_lua table
---@field check_list boolean
---@field activated boolean
---@field surf_reactor_normal number
---@field list_reactor table
---@field position_x number
---@field size_y number
---@field sort_items number
---@field my_window number
---@field move_y number
---@field st_lua table
---@field scroll number
---@field number_of_deleted number
---@field item_height number
---@field number_of_items number