---This is an auto generated class definition.
---
---Please use the found values as a starting point for your use.
---As not all values may be present at every point of the game.
---Or values could be missing from the definition.
---@class game_obj_research_panel
---@field activated boolean
---@field array_lua table
---@field base_size_h number
---@field double_click boolean
---@field last_m_x number
---@field last_x number
---@field last_y number
---@field max_size_x number
---@field min_size_x number
---@field mres table contains the research items that will be put on the research tree, does not contain the reference to the current research state see game_research_item for that
---@field number_of_res number
---@field old_ms_x number
---@field old_ms_y number
---@field research_desc_move number
---@field research_surf number
---@field size_ratio number
---@field size_x number
---@field size_y number
---@field sp_zoom number
---@field st_lua table
---@field tree_number number
---@field tree_slot_height number
---@field tree_slot_width number
---@field tree_width number