---This is an auto generated class definition.
---
---Please use the found values as a starting point for your use.
---As not all values may be present at every point of the game.
---Or values could be missing from the definition.
---@class game_obj_big_holder
---@field activated boolean
---@field armor_layers number
---@field armor_lr table
---@field armor_lr_have table
---@field armor_lr_have_copy table
---@field array_lua table
---@field camera_zoom number
---@field change boolean
---@field change_item_time number
---@field clean boolean
---@field cur_item number
---@field cur_item_type number
---@field cur_sprite number
---@field cur_sprite_start number
---@field cur_sprite_stop number
---@field cur_sprite_work number
---@field discket_active_armor number
---@field discket_ammo_ratio_red number
---@field discket_ammo_ratio_white number
---@field discket_ammo_ratio_yellow number
---@field discket_destruct number
---@field discket_energy_shield number
---@field discket_melee number
---@field ignite_open boolean
---@field mech_extra_layer number
---@field monitor_img number
---@field new_item number
---@field new_item_type number
---@field processor_program_researched boolean
---@field reactor_type number
---@field reactor_type_anim number
---@field save_blueprint_animation number
---@field scroll number
---@field send_open boolean
---@field st_lua table
---@field test_copy_surf number
---@field test_surf number
---@field text_battle_cost string
---@field text_blueprint_empty string
---@field text_blueprint_have string
---@field text_blueprint_type string
---@field text_menu_energy string
---@field text_menu_ignite string
---@field text_menu_reload string
---@field text_menu_send string
---@field text_menu_test string
---@field text_menu_weight string
---@field walk_holder table