---This is an auto generated class definition.
---
---Please use the found values as a starting point for your use.
---As not all values may be present at every point of the game.
---Or values could be missing from the definition.
---@class game_obj_content_pilots
---@field activated boolean
---@field array_lua table
---@field dead_pilots_array table
---@field dead_pilots_number number
---@field hospital_cyborg_one number
---@field hospital_cyborg_two number
---@field item_height number
---@field list_pilot game_obj_pilot_item[]
---@field memorial_animation number
---@field memorial_move_y number
---@field memorial_wall_active boolean
---@field move_y number
---@field my_window number
---@field number_of_deleted number
---@field number_of_items number
---@field play_sound_cyborgization number
---@field position_x number
---@field position_y number
---@field rm_hospital_one number
---@field rm_hospital_two number
---@field rm_training number
---@field scroll number
---@field size_x number
---@field size_y number
---@field sort_now boolean
---@field sort_pilots number
---@field st_lua table
---@field surf_pilots_normal number
---@field talent_text table
---@field text_age string
---@field text_average string
---@field text_reaction string
---@field text_stress string
---@field text_success string
---@field text_test string
---@field text_vitality string