---This is an auto generated class definition.
---
---Please use the found values as a starting point for your use.
---As not all values may be present at every point of the game.
---Or values could be missing from the definition.
---@class game_obj_safety_item
---@field created boolean
---@field deleted boolean
---@field hover boolean
---@field item_pos number
---@field load_ini boolean
---@field my_holder number
---@field my_mech number
---@field my_num number
---@field name string
---@field name_slowdown_multiplier string
---@field new_module boolean
---@field number_of_deleted number
---@field number_of_holders number
---@field safety_number number
---@field safety_spr number
---@field start_x number
---@field start_y number
---@field stat_slowdown_multiplier number