---This is an auto generated class definition.
---
---Please use the found values as a starting point for your use.
---As not all values may be present at every point of the game.
---Or values could be missing from the definition.
---@class game_obj_magnet_item
---@field created boolean
---@field deleted boolean
---@field hover boolean
---@field item_pos number
---@field load_ini boolean
---@field magnet_number number
---@field magnet_spr number
---@field my_holder number
---@field my_mech number
---@field my_num number
---@field name string
---@field name_move_x string
---@field name_move_y string
---@field name_move_z string
---@field new_module boolean
---@field number_of_deleted number
---@field number_of_holders number
---@field start_x number
---@field start_y number
---@field stat_move_x number
---@field stat_move_y number
---@field stat_move_z number