---This is an auto generated class definition.
---
---Please use the found values as a starting point for your use.
---As not all values may be present at every point of the game.
---Or values could be missing from the definition.
---@class game_obj_motor_item
---@field buf_wire_minus number
---@field buf_wire_plus number
---@field created boolean
---@field deleted boolean
---@field hover boolean
---@field item_pos number
---@field load_ini boolean
---@field motor_number number
---@field motor_spr number
---@field my_holder number
---@field my_mech number
---@field my_num number
---@field name string
---@field name_energy string
---@field name_power string
---@field name_speed string
---@field name_weight string
---@field new_module boolean
---@field number_of_deleted number
---@field number_of_holders number
---@field original_stat_energy number
---@field original_stat_power number
---@field start_x number
---@field start_y number
---@field stat_energy number
---@field stat_power number
---@field stat_speed number
---@field stat_weight number