---This is an auto generated class definition.
---
---Please use the found values as a starting point for your use.
---As not all values may be present at every point of the game.
---Or values could be missing from the definition.
---@class game_obj_weapon_test
---@field activated boolean
---@field armor_buf number
---@field current_type number
---@field damage_mass table
---@field damage_nmbr number
---@field gun_id number
---@field hit_mass table
---@field hit_nmbr number
---@field load_ini boolean
---@field miss_mass table
---@field miss_nmbr number
---@field monitor_img number
---@field move_x number
---@field overall_damage number
---@field overall_damage_mass table
---@field scroll number
---@field show_energy_sim number
---@field simulate_aux number
---@field simulate_energy number
---@field single_mod number
---@field start number
---@field target number
---@field test_copy_surf number
---@field test_reload_time_red number
---@field test_reload_time_white number
---@field test_reload_time_yellow number
---@field test_surf number
---@field text_accuracy string
---@field text_damage string
---@field text_dest_armor string
---@field text_hits string
---@field text_misses string
---@field text_pot_damage string
---@field text_shots string
---@field water_mod number
---@field weapon_description table