---This is an auto generated class definition.
---
---Please use the found values as a starting point for your use.
---As not all values may be present at every point of the game.
---Or values could be missing from the definition.
---@class game_obj_weapon_item
---@field accuracy_fault number
---@field blue_length number
---@field buf_wire_minus number
---@field buf_wire_plus number
---@field check_special boolean
---@field created boolean
---@field deleted boolean
---@field energy_buffed boolean
---@field homing_power number
---@field hover boolean
---@field item_pos number
---@field my_holder number
---@field my_mech number
---@field my_num number
---@field name string
---@field new_module boolean
---@field number_of_deleted number
---@field number_of_holders number
---@field original_accuracy number
---@field original_damage number
---@field original_energy number
---@field original_penetration number
---@field original_rate_of_fire number
---@field original_speed number
---@field original_weight number
---@field pretend_gun number
---@field rate_of_fire number
---@field set_point_accuracy number
---@field set_point_current number
---@field set_point_energy number
---@field set_point_fire_speed number
---@field set_point_max number
---@field set_point_penetration number
---@field set_point_weight number
---@field size_huge boolean
---@field sound_pack number
---@field special_acc_buf number
---@field special_buf_slow number
---@field special_buf_type number
---@field special_dmg_buf number
---@field special_ele_buf number
---@field special_num_buf number
---@field special_pen_buf number
---@field special_rtf_buf number
---@field special_weight_buf number
---@field start_x number
---@field start_y number
---@field stat_damage number
---@field stat_dps number
---@field stat_energy number
---@field stat_penetration number
---@field stat_weight number
---@field weapon_number number
---@field weapon_spr number
---@field weapon_spr_big number
---@field weapon_type string
---@field weapon_type_num number
---@field wep_prior table